name: Create_branch_when_issues
on:
    issues: 
        types:
            - assigned

jobs:
    create_issue_branch:
        runs-on: ubuntu-latest
        steps:
            - name: créer la branche de l'issue
              if: github.head_ref == 'develop'
              run: |
                git checkout develop
                git pull origin develop
                git checkout -b "feature/${{ github.event.issue.number }}-${{ github.event.issue.title }}"
              
              